name: Rust Continuous Integration
on:
  push:
    branches:
      - main
    paths-ignore:
      - "app/web/**"
      - "package.json"
      - "yarn.lock"
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run lint
        run: cargo build --release

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Style check
        run: cargo fmt --check --all --verbose

      - name: Clippy
        run: cargo clippy
